M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu22.04.1} date 2024-10-27T10:41:59+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-27T10:41:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X7.4646Y-4.3701
X7.7323Y-4.3701
M30
